# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rNdJNx4qwxe8l0Ko9J8NW0z7btUncVoa
"""

# 1- Crie uma lista chamada numeros que contenha os números inteiros de 1 a 5 e imprima-a na tela:
numeros = [1, 2, 3, 4, 5] #lista simples
print(numeros)

# 2- Acesse e imprima o terceiro elemento da lista numeros:
terceiro_elemento = numeros[3]
print(terceiro_elemento)

# 3- Adicione o número 6 à lista numeros e imprima a lista atualizada:
numeros.append(6) # .append() adiciona elementos
print(numeros)

# 4- Remova o número 3 da lista numeros e imprima a lista resultante:
numeros.remove(3)#remove o elemento desejado(direto) da lista
print(numeros)
del numeros[3] #deleta o elemento por meio da sua posição "índece"
print(numeros)

# 5- Crie uma lista chamada `frutas` contendo três nomes de frutas diferentes.
#    Em seguida, concatene essa lista com a lista `numeros` e imprima o resultado:
frutas = ['manga', 'banana', 'morango'] #forma correta de escrever listas com carateres(palavras): [] e " ", sendo ["xxx", "xxx", "xxx"]
print(frutas, numeros)

# 6- Use um loop for para percorrer e imprimir todos os elementos da lista frutas:
for n in frutas:
  print(n)

# 7- Verifique se o número 5 está presente na lista `numeros` e imprima
#    uma mensagem informando se ele está na lista ou não:

n1 = [1, 3, 6, 5, 25, 16]
print('O número', n1[3], 'está presente na lista.'  )